[providers]
nodejs = "22"

[phases.setup]
nixPkgs = ["nodejs_22", "yarn"]

[phases.install]
cmds = ["yarn install --frozen-lockfile"]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "node ./dist/server/entry.mjs" 